### ISSUE TITLE
Roberto - app with checklist and a DataTable

### ISSUE THREAD

**Issue by Coding-with-Adam** [AnnMarieW/dash-app-gallery#1]
app with checklist that has options of days that filters a DataTable. 

- [ ] Layout- 1row:1col;  1row:2col;  2row:1col;  3row:1col;  multiple row and col
- [ ] Callback- 1input:1output;  2input:1output;  1input:2output;  Multiple output input 
- [ ] Components - dropdown, checklist, DataTable, RadioItem,
- [ ] Data set - sports, geology, manufacturing, finance, general
- [ ] Graph- Bar, Line, Histogram, Scatter, Pie, Candle, etc

**Comment by rpanai** [comment]
Hi @Coding-with-Adam, I just pushed my changes. I'm not sure about dataset field. Do you mind to check?
