### ISSUE TITLE
Todo List for June 16

### ISSUE THREAD

**Issue by Coding-with-Adam** [AnnMarieW/dash-app-gallery#44]
- [x] @tolgahancepel: build 1-2 apps with missing elements from [community app list](https://docs.google.com/spreadsheets/d/1-ezhib_RuwSDckDM2znEkIutO7MEOltQYqkc_61zUcU/edit?usp=sharing).
- [x] @milanzmitrovic: build 1-2 apps with missing elements from [community app list](https://docs.google.com/spreadsheets/d/1-ezhib_RuwSDckDM2znEkIutO7MEOltQYqkc_61zUcU/edit?usp=sharing).
- [x] @someshfengde: Create a PR to add missing dependencies (keep dmc out for now) to requirements.txt file
- [x] @someshfengde:  Create 1 app from the community app list.
- [x] @rpanai:  Create a docker with explanation on how a contributor would use it, and create 1 app from the community app list.
- [x] @AnnMarieW: Add the "Featured Apps" dropdown; add the footnote with contributors; add margins on the sides of main page; see if Input search component can read multiple words inside the searched string.
- [x] @Coding-with-Adam: update contributing file: encourage contributors to use [Plotly's datasets](https://github.com/plotly/datasets) or add data to that repo if they prefer their own data; and add PR youtbe video for those that don't know how to fork a repo. 
- [x] @Coding-with-Adam: Finish intro text inside textbox on main page (add dash club oppo in there as well and link if they would like to contribute apps, and if they catch an error email me to report it)
- [x] @Coding-with-Adam: Talk to Chris about which repo to use to store data files

**Comment by someshfengde** [comment]
hi @Coding-with-Adam @AnnMarieW  I've just tried to install `dash mantine components` library 
for me, it's showing just 317kb  

I think we should consider adding it 
![image](https://user-images.githubusercontent.com/42097653/171691009-69f0bd46-900c-46af-bf96-3e2bcf2c644e.png)

**Comment by Coding-with-Adam** [comment]
ok @someshfengde That's pretty small. Then, I think we should move ahead with dash-mantine-components in the requirements.txt. And @AnnMarieW I'll update this issue so there is no need to update the datepicker back to dcc. We can leave it as mantine, just as you did it.

**Comment by someshfengde** [comment]
> * [ ]  @tolgahancepel: build 1-2 apps with missing elements from [community app list](https://docs.google.com/spreadsheets/d/1-ezhib_RuwSDckDM2znEkIutO7MEOltQYqkc_61zUcU/edit?usp=sharing).
> * [ ]  @milanzmitrovic: build 1-2 apps with missing elements from [community app list](https://docs.google.com/spreadsheets/d/1-ezhib_RuwSDckDM2znEkIutO7MEOltQYqkc_61zUcU/edit?usp=sharing).
> - [x]  @someshfengde: Create a PR to add missing dependencies (keep dmc out for now) to requirements.txt file
> * [ ]  @someshfengde: Create a PR to remove unused imported libraries in relevant apps, and create 1 app from the community app list.
> * [ ]  @rpanai:  Create a docker with explanation on how a contributor would use it, and create 1 app from the community app list.
> * [ ]  @AnnMarieW: Add the "Featured Apps" dropdown; add the footnote with contributors; add margins on the sides of main page; see if Input search component can read multiple words inside the searched string.
> * [ ]  @Coding-with-Adam: update contributing file with info about Black and Lint and encourage contributors to use [Plotly's datasets](https://github.com/plotly/datasets).
> * [ ]  @Coding-with-Adam: Talk to Chris about which repo to use to store data files

**Comment by someshfengde** [comment]
google sheet link 
https://docs.google.com/spreadsheets/d/1-ezhib_RuwSDckDM2znEkIutO7MEOltQYqkc_61zUcU/edit?usp=sharing

**Comment by Coding-with-Adam** [comment]
hey team,
for those of you that would like to use external data sets, we should try to use the data sets encountered in this [Plotly repo](https://github.com/plotly/datasets). And if you prefer your own data set, please add them to that repo through a PR. 
I'll update the contributor's guide with this new information.

**Comment by Coding-with-Adam** [comment]
Todo list:
- remove search field tooltip and modify input label to "Search Code"
- move accordion under Search Code input field. And put text box to the right.
- add footnote of names of all contributors
- add `link_target='_blank'` to notes so it opens in new tab
- Change Callback Type and Figure Type to "Callbacks" and "Figures".
- modify callbacks to say All and add ctx
- Also search description in pages.py folder to create links for Featured Apps  
- From components (in Featured apps), remove dbc and dmc, and just read the components itself.

**Comment by rpanai** [comment]
Hi all,
I was building a docker. At first I thought to prepare one just to run the app and I then realize you asked me to build something contributors could use. Could Jupyter-Lab be a viable environment for contributors or not?
At the moment I'm dealing with a port (8050) exposure and docker image size. To my understanding we should try to use less than 500MB. Am I wrong here?

**Comment by IcToxi** [comment]
Don't worry too much about the library files size because of Heroku's unique compression technology. In one of my repositories I imported those large packages including sklearn and pandas, when it was made into docker it took up more than one GB, but it was only 288 MB after Heroku compressed.

**Comment by someshfengde** [comment]
Hi, @IcToxi  let me know if you have created the docker file and can you share that with me.

**Comment by IcToxi** [comment]
Hi @someshfengde, you can refer to [this](https://community.plotly.com/t/daily-tips-how-many-ways-to-share-dash-in-a-company/62934?u=stu) as this repo is also prepared for Heroku.

**Comment by someshfengde** [comment]
thanks

**Comment by IcToxi** [comment]
- [x] Format code examples with black 21.6b0 to match the dash repo

https://github.com/AnnMarieW/dash-app-gallery/pull/40/commits/7c42f4063e38ffcbad35ba200d5b1ee0ffa555e8

**Comment by Coding-with-Adam** [comment]
Let's see what @IcToxi says, but I think we can stop here since Heroku has good file compression technology

**Comment by rpanai** [comment]
Regarding the docker the command is:

```bash
docker pull rpanai/dash-app-gallery:latest \
&& docker run -p 8050:8050 rpanai/dash-app-gallery:latest
```
Then you can browse the app at [http://127.0.0.1:8050/](http://127.0.0.1:8050/).

The image is [here](https://hub.docker.com/layers/238194737/rpanai/dash-app-gallery/latest/images/sha256-e1f798a801faff31c33744bb4003e1c05f3b1cb5e7ad526bb6d463cc9babbb73?context=repo) and compressed is less than 300MB.

**Comment by IcToxi** [comment]
@rpanai 

That was a post I wrote a month ago, not for this project, but just to provide an idea. And I mentioned in the post, it has nothing to do with the package manager, you can replace it, for example, it can be poetry.

**Comment by Coding-with-Adam** [comment]
Hi @rpanai 
I just emailed you so we can connect regarding the docker

**Comment by Coding-with-Adam** [comment]
Finished all projects in this issue. Docker for developers to run app will be opened as a separate issue by Roberto.
